{
    "current_index": 3,
    "name": "Math×Girl",
    "problems": [
        {
            "cases": [
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/1.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/1.in",
                    "name": "1"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/2.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/2.in",
                    "name": "2"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/3.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/3.in",
                    "name": "3"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/4.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/4.in",
                    "name": "4"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/5.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/5.in",
                    "name": "5"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/6.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/6.in",
                    "name": "6"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/7.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/7.in",
                    "name": "7"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/8.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/8.in",
                    "name": "8"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/9.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/9.in",
                    "name": "9"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/10.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/10.in",
                    "name": "10"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/11.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/11.in",
                    "name": "11"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/12.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/12.in",
                    "name": "12"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/13.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/13.in",
                    "name": "13"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/14.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/14.in",
                    "name": "14"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/15.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/15.in",
                    "name": "15"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/16.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/16.in",
                    "name": "16"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/17.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/17.in",
                    "name": "17"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/18.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/18.in",
                    "name": "18"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/19.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/19.in",
                    "name": "19"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/20.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/距离/test/20.in",
                    "name": "20"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:22px; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
            "memory_limit": 0,
            "memory_limit_unit": 1,
            "name": "距离",
            "time_limit": 0,
            "time_limit_unit": 0,
            "url": ""
        },
        {
            "cases": [
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/1.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/1.in",
                    "name": "1"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/2.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/2.in",
                    "name": "2"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/3.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/3.in",
                    "name": "3"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/4.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/4.in",
                    "name": "4"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/5.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/5.in",
                    "name": "5"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/6.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/6.in",
                    "name": "6"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/7.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/7.in",
                    "name": "7"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/8.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/8.in",
                    "name": "8"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/9.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/9.in",
                    "name": "9"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/10.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/10.in",
                    "name": "10"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/11.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/11.in",
                    "name": "11"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/12.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/12.in",
                    "name": "12"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/13.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/13.in",
                    "name": "13"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/14.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/14.in",
                    "name": "14"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/15.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/15.in",
                    "name": "15"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/16.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/16.in",
                    "name": "16"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/17.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/17.in",
                    "name": "17"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/18.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/18.in",
                    "name": "18"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/19.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/19.in",
                    "name": "19"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/20.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/平均律/test/20.in",
                    "name": "20"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:22px; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
            "memory_limit": 0,
            "memory_limit_unit": 1,
            "name": "平均律",
            "time_limit": 0,
            "time_limit_unit": 0,
            "url": ""
        },
        {
            "cases": [
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/1.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/1.in",
                    "name": "1"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/2.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/2.in",
                    "name": "2"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/3.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/3.in",
                    "name": "3"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/4.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/4.in",
                    "name": "4"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/5.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/5.in",
                    "name": "5"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/6.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/6.in",
                    "name": "6"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/7.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/7.in",
                    "name": "7"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/8.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/8.in",
                    "name": "8"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/9.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/9.in",
                    "name": "9"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/10.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/10.in",
                    "name": "10"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/11.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/11.in",
                    "name": "11"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/12.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/12.in",
                    "name": "12"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/13.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/13.in",
                    "name": "13"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/14.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/14.in",
                    "name": "14"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/15.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/15.in",
                    "name": "15"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/16.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/16.in",
                    "name": "16"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/17.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/17.in",
                    "name": "17"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/18.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/18.in",
                    "name": "18"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/19.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/19.in",
                    "name": "19"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/20.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/互质与整除/test/20.in",
                    "name": "20"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:22px; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
            "memory_limit": 0,
            "memory_limit_unit": 1,
            "name": "互质与整除",
            "time_limit": 0,
            "time_limit_unit": 0,
            "url": ""
        },
        {
            "cases": [
                {
                    "expected": "1\n1\n4\n1\n8\n9\n1\n12\n21\n16\n1\n20\n33\n40\n25\n6\n14\n36\n30\n140\n120\n62\n356\n576\n300\n",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/1.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/1.in",
                    "name": "1"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/2.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/2.in",
                    "name": "2"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/3.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/3.in",
                    "name": "3"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/4.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/4.in",
                    "name": "4"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/5.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/5.in",
                    "name": "5"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/6.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/6.in",
                    "name": "6"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/7.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/7.in",
                    "name": "7"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/8.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/8.in",
                    "name": "8"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/9.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/9.in",
                    "name": "9"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/10.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/10.in",
                    "name": "10"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/11.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/11.in",
                    "name": "11"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/12.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/12.in",
                    "name": "12"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/13.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/13.in",
                    "name": "13"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/14.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/14.in",
                    "name": "14"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/15.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/15.in",
                    "name": "15"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/16.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/16.in",
                    "name": "16"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/17.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/17.in",
                    "name": "17"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/18.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/18.in",
                    "name": "18"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/19.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/19.in",
                    "name": "19"
                },
                {
                    "expected": "",
                    "expected_output_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/20.out",
                    "input": "",
                    "input_filename": "C:/Users/Naszt/Desktop/sci/article/OI/problem/Math×Girl/2.0/染色/test/20.in",
                    "name": "20"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:22px; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
            "memory_limit": 0,
            "memory_limit_unit": 1,
            "name": "染色",
            "time_limit": 0,
            "time_limit_unit": 0,
            "url": ""
        }
    ]
}
