1.in:
  subtaskId: 0
  score: 5

2.in:
  subtaskId: 1
  score: 15

3.in:
  subtaskId: 1
  score: 15

4.in:
  subtaskId: 1
  score: 15

5.in:
  subtaskId: 2
  score: 15

6.in:
  subtaskId: 2
  score: 15

7.in:
  subtaskId: 2
  score: 15

8.in:
  subtaskId: 3
  score: 10

9.in:
  subtaskId: 3
  score: 10

10.in:
  subtaskId: 4
  score: 15

11.in:
  subtaskId: 4
  score: 15

12.in:
  subtaskId: 4
  score: 15

13.in:
  subtaskId: 5
  score: 15

14.in:
  subtaskId: 5
  score: 15

15.in:
  subtaskId: 5
  score: 15

16.in:
  subtaskId: 6
  score: 25

17.in:
  subtaskId: 6
  score: 25

18.in:
  subtaskId: 6
  score: 25

19.in:
  subtaskId: 6
  score: 25

20.in:
  subtaskId: 6
  score: 25

