1.in:
  subtaskId: 0
  score: 10

2.in:
  subtaskId: 0
  score: 10

3.in:
  subtaskId: 0
  score: 10

4.in:
  subtaskId: 0
  score: 10

5.in:
  subtaskId: 1
  score: 20

6.in:
  subtaskId: 1
  score: 20

7.in:
  subtaskId: 1
  score: 20

8.in:
  subtaskId: 1
  score: 20

9.in:
  subtaskId: 2
  score: 70

10.in:
  subtaskId: 2
  score: 70

11.in:
  subtaskId: 2
  score: 70

12.in:
  subtaskId: 2
  score: 70

13.in:
  subtaskId: 2
  score: 70

14.in:
  subtaskId: 2
  score: 70

15.in:
  subtaskId: 2
  score: 70

16.in:
  subtaskId: 2
  score: 70

17.in:
  subtaskId: 2
  score: 70

18.in:
  subtaskId: 2
  score: 70

19.in:
  subtaskId: 2
  score: 70

20.in:
  subtaskId: 2
  score: 70

