1.in:
  subtaskId: 0
  score: 10

2.in:
  subtaskId: 0
  score: 10

3.in:
  subtaskId: 1
  score: 15

4.in:
  subtaskId: 1
  score: 15

5.in:
  subtaskId: 1
  score: 15

6.in:
  subtaskId: 2
  score: 25

7.in:
  subtaskId: 2
  score: 25

8.in:
  subtaskId: 2
  score: 25

9.in:
  subtaskId: 2
  score: 25

10.in:
  subtaskId: 2
  score: 25

11.in:
  subtaskId: 3
  score: 50

12.in:
  subtaskId: 3
  score: 50

13.in:
  subtaskId: 3
  score: 50

14.in:
  subtaskId: 3
  score: 50

15.in:
  subtaskId: 3
  score: 50

16.in:
  subtaskId: 3
  score: 50

17.in:
  subtaskId: 3
  score: 50

18.in:
  subtaskId: 3
  score: 50

19.in:
  subtaskId: 3
  score: 50

20.in:
  subtaskId: 3
  score: 50

